[book]
authors = ["Niko Matsakis"]
language = "en"
src = "md"
title = "Symposium"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.rfd]
command = "./md-rfd-preprocessor/target/release/md-rfd-preprocessor"

[output]

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
