[book]
authors = ["Niko Matsakis"]
language = "en"
src = "md"
title = "Symposium"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.rfd]
command = "cargo run -p md-rfd-preprocessor --"

[output]

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
fold.enable = true
fold.level = 0
